/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/episode-detail`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/timeline`; params?: Router.UnknownInputParams; } | { pathname: `/vet-summary`; params?: Router.UnknownInputParams; } | { pathname: `/quick-add/add-medication`; params?: Router.UnknownInputParams; } | { pathname: `/../context/medication-draft`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/quick-add/capture`; params?: Router.UnknownInputParams; } | { pathname: `/quick-add/reminder`; params?: Router.UnknownInputParams; } | { pathname: `/quick-add/review`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/episode-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/timeline`; params?: Router.UnknownOutputParams; } | { pathname: `/vet-summary`; params?: Router.UnknownOutputParams; } | { pathname: `/quick-add/add-medication`; params?: Router.UnknownOutputParams; } | { pathname: `/../context/medication-draft`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/quick-add/capture`; params?: Router.UnknownOutputParams; } | { pathname: `/quick-add/reminder`; params?: Router.UnknownOutputParams; } | { pathname: `/quick-add/review`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/episode-detail${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/timeline${`?${string}` | `#${string}` | ''}` | `/vet-summary${`?${string}` | `#${string}` | ''}` | `/quick-add/add-medication${`?${string}` | `#${string}` | ''}` | `/../context/medication-draft${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/quick-add/capture${`?${string}` | `#${string}` | ''}` | `/quick-add/reminder${`?${string}` | `#${string}` | ''}` | `/quick-add/review${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/episode-detail`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/timeline`; params?: Router.UnknownInputParams; } | { pathname: `/vet-summary`; params?: Router.UnknownInputParams; } | { pathname: `/quick-add/add-medication`; params?: Router.UnknownInputParams; } | { pathname: `/../context/medication-draft`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/quick-add/capture`; params?: Router.UnknownInputParams; } | { pathname: `/quick-add/reminder`; params?: Router.UnknownInputParams; } | { pathname: `/quick-add/review`; params?: Router.UnknownInputParams; };
    }
  }
}
